const {
    queryGetAllRequests,
    queryGetAllUniqueShifts,
    queryGetDayNotes,
    queryGetNonShiftGroupMembers,
    queryGetRequests,
    queryGetSettings,
    queryGetSharedSchedules,
    queryGetShiftGroupMembers,
    queryGetShiftGroups,
    queryGetShiftsByPeople,
    queryGetShiftsByTask,
} = require('./Query');

const {
    mutationAssignedShiftAdd,
    mutationAssignedShiftDelete,
    mutationAssignedShiftEdit,
    mutationAssignedShiftMoveToOpen,
    mutationAssignedShiftShare,
    mutationCancelRequestOffer,
    mutationCancelRequestSwap,
    mutationDayNoteUpdate,
    mutationOpenShiftAdd,
    mutationOpenShiftAssign,
    mutationOpenShiftDelete,
    mutationOpenShiftEdit,
    mutationRecallSharedSchedules,
    mutationRequestCreateOffer,
    mutationRequestCreateSwap,
    mutationRequestCreateTimeOff,
    mutationShiftGroupCreate,
    mutationShiftGroupDelete,
    mutationShiftGroupMemberAdd,
    mutationShiftGroupMemberRemove,
    mutationShiftGroupMembersReorder,
    mutationShiftGroupRename,
    mutationShiftGroupReorder,
    mutationTimeOffAdd,
    mutationTimeOffDelete,
    mutationTimeOffEdit,
    mutationUpdateSettings,
} = require('./Mutation');

const {
    userPrivateMetafield,
    userPrivateMetafields,
    userMetafield,
    userMetafields,
} = require('./User');

module.exports = {
    Query: {
        getShiftGroups: queryGetShiftGroups,
        getShiftGroupMembers: queryGetShiftGroupMembers,
        getNonShiftGroupMembers: queryGetNonShiftGroupMembers,
        getShiftsByPeople: queryGetShiftsByPeople,
        getShiftsByTask: queryGetShiftsByTask,
        getSharedSchedules: queryGetSharedSchedules,
        getAllUniqueShifts: queryGetAllUniqueShifts,
        getRequests: queryGetRequests,
        getAllRequests: queryGetAllRequests,
        getDayNotes: queryGetDayNotes,
        getSettings: queryGetSettings,
    },
    Mutation: {
        shiftGroupCreate: mutationShiftGroupCreate,
        shiftGroupReorder: mutationShiftGroupReorder,
        shiftGroupRename: mutationShiftGroupRename,
        shiftGroupDelete: mutationShiftGroupDelete,
        shiftGroupMemberAdd: mutationShiftGroupMemberAdd,
        shiftGroupMembersReorder: mutationShiftGroupMembersReorder,
        shiftGroupMemberRemove: mutationShiftGroupMemberRemove,
        assignedShiftAdd: mutationAssignedShiftAdd,
        assignedShiftEdit: mutationAssignedShiftEdit,
        assignedShiftDelete: mutationAssignedShiftDelete,
        assignedShiftMoveToOpen: mutationAssignedShiftMoveToOpen,
        assignedShiftShare: mutationAssignedShiftShare,
        recallSharedSchedules: mutationRecallSharedSchedules,
        openShiftAdd: mutationOpenShiftAdd,
        openShiftEdit: mutationOpenShiftEdit,
        openShiftDelete: mutationOpenShiftDelete,
        openShiftAssign: mutationOpenShiftAssign,
        timeOffAdd: mutationTimeOffAdd,
        timeOffEdit: mutationTimeOffEdit,
        timeOffDelete: mutationTimeOffDelete,
        dayNoteUpdate: mutationDayNoteUpdate,
        requestCreateTimeOff: mutationRequestCreateTimeOff,
        requestCreateSwap: mutationRequestCreateSwap,
        requestCreateOffer: mutationRequestCreateOffer,
        cancelRequestSwap: mutationCancelRequestSwap,
        cancelRequestOffer: mutationCancelRequestOffer,
        updateSettings: mutationUpdateSettings
    },
    User: {
        privateMetafield: userPrivateMetafield,
        privateMetafields: userPrivateMetafields,
        metafield: userMetafield,
        metafields: userMetafields,
    },
};