export const LANGUAGES = [
  `English (United States) `,
  `Bulgarian (Български) `,
  `Czech (Česky) `,
  `Dansk `,
  `Greek (Ελληνικά) `,
  `Eesti `,
  `English (Canada) `,
  `English (Great Britain) `,
  `Español `,
  `Español (Colombia) `,
  `Español (México) `,
  `Suomi `,
  `Français `,
  `Français (Canada) `,
  `Hrvatski `,
  `Magyar `,
  `Italiano `,
  `Japanese (日本語) `,
  ` Lietuvių kalba `,
  `Latvijas `,
  `Norsk bokmål `,
  `Nederlands `,
  `Polski `,
  `Português `,
  `Português Brasileiro `,
  `Russian (Русский) `,
  `Slovak (Slovenčina) `,
  `Slovenian (Slovenčina) `,
  `Svenska `,
  `Türkçe `,
  `Ukrainian (Українська) `,
  `Vietnam (ViɆt Nam) `,
  `Chinese (Sim.) (简体中文) `,
  `Hindi (हिंदी) `,
  `Deutsch `,
  `Hebrew (עִבְרִית) `,
  `Persian (فارسى) `,
  `Malay (Bahasa Malaysia) `,
  `Romanian (Românesc) `,
  `Arabic `,
  `Serbian (srpski) `,
  `Icelandic (Íslenska) `,
  `Ikinyarwanda `,
  `Korean (한국어) `,
  `Català `,
  `Chinese (Trad.) (繁體中文) `
]
