const db = {
    account_user: "account_user",
    account_address: "account_address",
    account_user_addresses: "account_user_addresses",

    auth_group: "auth_group",
    auth_permissions: "auth_permission",
    auth_group_permissions: "auth_group_permissions",
    account_user_groups: "account_user_groups",
    account_user_user_permissions: "account_user_user_permissions",

    attribute_assignedproductattribute: "attribute_assignedproductattribute",
    attribute_assignedproductattributevalue: "attribute_assignedproductattributevalue",
    attribute_assignedvariantattribute: "attribute_assignedvariantattribute",
    attribute_assignedvariantattributevalue: "attribute_assignedvariantattributevalue",
    attribute_assignedpageattribute: "attribute_assignedpageattribute",
    attribute_assignedpageattributevalue: "attribute_assignedpageattributevalue",
    attribute_attribute: "attribute_attribute",
    attribute_attributepage: "attribute_attributepage",
    attribute_attributeproduct: "attribute_attributeproduct",
    attribute_attributetranslation: "attribute_attributetranslation",
    attribute_attributevalue: "attribute_attributevalue",
    attribute_attributevaluetranslation: "attribute_attributevaluetranslation",
    attribute_attributevariant: "attribute_attributevariant",
    checkout_checkout: "checkout_checkout",
    checkout_checkoutline: "checkout_checkoutline",
    checkout_checkout_gift_cards: "checkout_checkout_gift_cards",
    discount_voucher: "discount_voucher",
    discount_voucherchannellisting: "discount_voucherchannellisting",
    discount_voucher_collections: "discount_voucher_collections",
    discount_voucher_categories: "discount_voucher_categories",
    discount_vouchercustomer: "discount_vouchercustomer",
    discount_vouchertranslation: "discount_vouchertranslation",
    discount_voucher_products: "discount_voucher_products",
    discount_voucher_variants: "discount_voucher_variants",
    discount_sale_products: "discount_sale_products",
    discount_sale_variants: "discount_sale_variants",
    discount_sale: "discount_sale",
    discount_sale_categories: "discount_sale_categories",
    discount_sale_collections: "discount_sale_collections",
    discount_salechannellisting: "discount_salechannellisting",
    discount_saletranslation: "discount_saletranslation",
    giftcard_giftcard: "giftcard_giftcard",
    giftcard_giftcard_tags: "giftcard_giftcard_tags",
    giftcard_giftcardevent: "giftcard_giftcardevent",
    giftcard_giftcardtag: "giftcard_giftcardtag",
    menu_menu: "menu_menu",
    menu_menuitem: "menu_menuitem",
    menu_menuitemtranslation: "menu_menuitemtranslation",
    order_order: "order_order",
    order_orderline: "order_orderline",
    order_fulfillment: "order_fulfillment",
    order_fulfillmentline: "order_fulfillmentline",
    payment_payment: "payment_payment",
    payment_transaction: "payment_transaction",
    page_page: "page_page",
    page_pagetranslation: "page_pagetranslation",
    page_pagetype: "page_pagetype",
    product_category: "product_category",
    product_categorytranslation: "product_categorytranslation",
    product_collection: "product_collection",
    product_collectionproduct: "product_collectionproduct",
    product_collectiontranslation: "product_collectiontranslation",
    product_collectionchannellisting: "product_collectionchannellisting",
    product_digitalcontent: "product_digitalcontent",
    product_digitalcontenturl: "product_digitalcontenturl",
    product_product: "product_product",
    product_productchannellisting: "product_productchannellisting",
    product_productmedia: "product_productmedia",
    product_producttranslation: "product_producttranslation",
    product_producttype: "product_producttype",
    product_productvariant: "product_productvariant",
    product_productvariantchannellisting: "product_productvariantchannellisting",
    product_productvarianttranslation: "product_productvarianttranslation",
    product_variantmedia: "product_variantmedia",
    shipping_shippingmethod: "shipping_shippingmethod",
    shipping_shippingmethodtranslation: "shipping_shippingmethodtranslation",
    shipping_shippingzone: "shipping_shippingzone",
    shipping_shippingzone_channels: "shipping_shippingzone_channels",
    shipping_shippingmethodpostalcoderule: "shipping_shippingmethodpostalcoderule",
    shipping_shippingmethodchannellisting: " shipping_shippingmethodchannellisting",
    shipping_shippingmethod_excluded_products: " shipping_shippingmethod_excluded_products",
    site_sitesettings: "site_sitesettings",
    site_sitesettingstranslation: "site_sitesettingstranslation",
    warehouse_warehouse_shipping_zones: "warehouse_warehouse_shipping_zones",
    warehouse_warehouse: "warehouse_warehouse",
    warehouse_stock: "warehouse_stock",
    warehouse_allocation: "warehouse_allocation",
    warehouse_reservation: "warehouse_reservation",

    app_app: "app_app",
    app_app_permissions: "app_app_permissions",
    app_appextension: "app_appextension",
};

const events = [
    "exit",
    "SIGINT",
    "SIGUSR1",
    "SIGUSR2",
    "SIGTERM",
    "uncaughtExecption"
];

module.exports = {
    db,
    events
};