GET http://88.208.199.175:1000/knowledgebase/getListStatus/knowledge_base_id/78/parent_id/878/kb_locale_id/1/list_name/dan

###

POST http://88.208.199.175:4000
Content-Type: application/json

{
    "query":"query { allLocales{nodes{id\nname}} }"
}


###
POST http://88.208.199.175:4000
Content-Type: application/json

{
    "query":"query { ping }"
}

###
POST http://88.208.199.175:4000
Content-Type: application/json

{
    "query":"{knowledgebases{id\nname\nicon}}"
}

### 
GET http://88.208.199.175:1000/knowledgebase/getKnowledgeBaseCategories/knowledge_base_id/78/kb_locale_id/1?page=1&limit=10&level=1

###
DELETE http://88.208.212.10:8080/function/testfunc
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###
GET http://88.208.212.10:8080/function/knowledgebase
Content-Type: 