POST http://88.208.199.175:2300/graphql
Content-Type: application/json
authorization-bearer: Bearer 329fcbcd-3cc8-43e1-aad7-b3e604
X-Request-Type: GraphQL

query ($id: ID!){
  permissionGroup(id: $id) {
    id
    name
    users {
      email
      firstName
      lastName
      userPermissions{
        code
      }
    }
    permissions {
      code
      name
    }
    userCanManage
  }
}

{
    "id": 1
}