POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREE1TENKbGJXRnBiQ0k2SW05dmVVQjJMbU52SWl3aWFXRjBJam94TmpVME56ZzJNVFExZlEuTGFzWTJSdlBLeXliYV95UUhVR28xMm1GSUdWUm9hUWJFbUFTS3Vwcmd6SSIsImlhdCI6MTY1NDc4NjE0NSwiZXhwIjoxNjU0Nzg2NDQ1LCJzdWIiOiIxMDA5In0.4jQ-9-5pm5VG_Y-mgtFEIs0ziscJLe_Wast-KGbCZ9g
X-Request-Type: GraphQL

mutation{
 tokensDeactivateAll{
    errors{
      field
      message
    }
  }
}


###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV3TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1ZVVCbmJXRnBiQzVqYjIwaUxDSnBZWFFpT2pFMk5UUTROakF5TWpWOS5pdVd2MUY5cnpYMXhta1l5ZWlqZFpBRWx4eWFMaTZJZnBpZjMzUGFZMkdnIiwiaWF0IjoxNjU0ODYwMjI1LCJleHAiOjE2NTQ4NjA1MjUsInN1YiI6IjEwMTAifQ.zbHHK0Goe7xltkyfO74S9qdd7ifuB_AzaiwOmvxMYvs
X-Request-Type: GraphQL

query {
  me{
    id
    email
    firstName
    lastName
    isStaff
    isActive
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EZzNOek14T1gwLlh1NTBNdXByb2d5Q3o1RFAzZEVJaWZTSkZNYUlMQzFkYXFVRE1ldERyd00iLCJpYXQiOjE2NTQ4NzczMTksImV4cCI6MTY1NDg3NzYxOSwic3ViIjoiMTAxMSJ9.tgL1ouJr6nHCWB0F3adpubHNh_X_tIC18w3ZFgJUhek
X-Request-Type: GraphQL

query{
  staffUsers{
    edges{
      node{
        email
      }
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazBPRGMxT0gwLmZIUGh3VFhLc0hldUlRVFpXUk14RkZCeDdHaWlTWjNRcFltVVprNzlJZE0iLCJpYXQiOjE2NTQ5NDg3NTgsImV4cCI6MTY1NDk0OTA1OCwic3ViIjoiMTAxMSJ9.OqqZywwv0VG7MuIITTSJHX9lp9aiTs6knx46XnSSogI
X-Request-Type: GraphQL

mutation AddressCreate($userId: ID!){
  addressCreate(userId: $userId, input: {
    firstName: "sam",
    lastName: "withw",
    companyName: "facebook",
    streetAddress1: "1 street abc",
    streetAddress2: "2 street abc",
    city: "cali",
    cityArea: "cali",
    postalCode: "90023",
    country: BN,
    countryArea: "",
    phone: ""
  }) {
    user{
      id
      email
    }
    address{
      id
      firstName
      city
    }
    accountErrors {
      field
      message
      code
    }
  }
}

{
  "userId": 1011
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazBPVFV3TW4wLjU4TjZUaGlnTTBaNVJPcDNJWmlyMVNhWmd5OHdzajE5Y3YyNEtWaXhMUzQiLCJpYXQiOjE2NTQ5NDk1MDIsImV4cCI6MTY1NDk0OTgwMiwic3ViIjoiMTAxMSJ9.NI1oHJ8lQIBJcOQUgmK8GCxniIXbv9MvuNEh-pA152c
X-Request-Type: GraphQL

mutation AddressUpdate{
  addressUpdate(id: 167, input: {
    lastName: "william"
  }) {
    user{
      id
      email
    }
    address{
      id
      firstName
      city
    }
    accountErrors {
      message
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EZzNOek14T1gwLlh1NTBNdXByb2d5Q3o1RFAzZEVJaWZTSkZNYUlMQzFkYXFVRE1ldERyd00iLCJpYXQiOjE2NTQ4NzczMTksImV4cCI6MTY1NDg3NzYxOSwic3ViIjoiMTAxMSJ9.tgL1ouJr6nHCWB0F3adpubHNh_X_tIC18w3ZFgJUhek
X-Request-Type: GraphQL

mutation AddressCreate{
  accountAddressCreate(input: {
    firstName: "sam",
    lastName: "withw",
    companyName: "facebook",
    streetAddress1: "1 street abc",
    streetAddress2: "2 street abc",
    city: "cali",
    cityArea: "cali",
    postalCode: "90023",
    country: BN,
    countryArea: "",
    phone: ""
  }) {
    user{
      id
      email
    }
    address{
      id
      firstName
      city
    }
    accountErrors {
      field
      message
      code
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EZzRNREUzTjMwLlc2RncyTFFGSEYtOGJSVlhUVWM3QVo5dHJfT1NCZXp5TXNFVDRrSXI1SVEiLCJpYXQiOjE2NTQ4ODAxNzcsImV4cCI6MTY1NDg4MDQ3Nywic3ViIjoiMTAxMSJ9.hdU8ci8mdXnQ_gmjdpmw064fH2swcbDVRBMbP-PL-Z8
X-Request-Type: GraphQL

mutation AddressUpdate{
  accountAddressUpdate(id: 160, input: {
    firstName: "sam",
    lastName: "withw",
    companyName: "facebook",
    streetAddress1: "1 street abc",
    streetAddress2: "2 street abc",
    city: "cali",
    cityArea: "cali",
    postalCode: "90023",
    country: BN,
    countryArea: "",
    phone: ""
  }) {
    user{
      id
      email
    }
    address{
      id
      firstName
      city
    }
    accountErrors {
      message
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EZzRNVEkwTW4wLnNMOWk5enI2TVhVdHBSTWRSTjVycm4zcnA0MFp5RlJ3WDdRcVBWZUNCZVkiLCJpYXQiOjE2NTQ4ODEyNDIsImV4cCI6MTY1NDg4MTU0Miwic3ViIjoiMTAxMSJ9.ZhPMggshfFpZJlQvgaAPkEaE6eyIcv8fAGGnRXfb5zQ
X-Request-Type: GraphQL

mutation AddressDelete{
  accountAddressDelete(id: 163) {
    user{
      id
      email
    }
    address{
      id
      firstName
      city
    }
    accountErrors {
      message
    }
  }
}


###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazFORFkwTkgwLncwRmlWc3RHNUw1bGc2NXJ4dEQ0Z0xTUl9mdlBNNW1CMEF4OXY2bmY2cG8iLCJpYXQiOjE2NTQ5NTQ2NDQsImV4cCI6MTY1NDk1NDk0NCwic3ViIjoiMTAxMSJ9.uwfcxRbjLDOhISZ5jeSB5X6rpUU58JxcrwN4kXiCBdA
X-Request-Type: GraphQL

mutation AddressDelete{
  addressDelete(id: 166) {
    user{
      id
      email
    }
    address{
      id
      firstName
      city
    }
    accountErrors {
      message
    }
  }
}



###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazFOVFV5Tm4wLkdjZFB0dUxnRzNSNkFDaDAtQVluZW1fWVJMOEtiU3lTaVlUVGVVUDhnZWMiLCJpYXQiOjE2NTQ5NTU1MjYsImV4cCI6MTY1NDk1NTgyNiwic3ViIjoiMTAxMSJ9.oN-eAW2TjSaw_1FqnGdHp87nhYbGRqPZbno7EymGqQk
X-Request-Type: GraphQL

mutation AddressSetDefault($addressId: ID!, $type: AddressTypeEnum!, $userId: ID!){
  addressSetDefault(addressId: $addressId, type: $type, userId: $userId) {
    user{
      id
      email
    }
    accountErrors {
      message
    }
  }
}

{
  "addressId": 167,
  "type": "BILLING",
  "userId": 1008
}
###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazFORFkwTkgwLncwRmlWc3RHNUw1bGc2NXJ4dEQ0Z0xTUl9mdlBNNW1CMEF4OXY2bmY2cG8iLCJpYXQiOjE2NTQ5NTQ2NDQsImV4cCI6MTY1NDk1NDk0NCwic3ViIjoiMTAxMSJ9.uwfcxRbjLDOhISZ5jeSB5X6rpUU58JxcrwN4kXiCBdA
X-Request-Type: GraphQL

mutation SetDefaultAddress($id: ID!, $type: AddressTypeEnum!){
  accountSetDefaultAddress(id: $id, type: $type) {
    user{
      id
      email
      defaultShippingAddress{
        id
      }
      defaultBillingAddress{
        id
      }
    }
    accountErrors {
      message
    }
  }
}

{
  "id": 166,
  "type": "SHIPPING"
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV3TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1ZVVCbmJXRnBiQzVqYjIwaUxDSnBZWFFpT2pFMk5UUTROakV3T1RKOS5DeE9OTk5YbTFCVzhXNFhQZFB5dmxoQ3k4dDdsVEljUENiNWxXakl0cEJRIiwiaWF0IjoxNjU0ODYxMDkyLCJleHAiOjE2NTQ4NjEzOTIsInN1YiI6IjEwMTAifQ.zJ8kVYuEhA4e4v2I-T2jjw08HSQBgzkfafIqjU83z4U
X-Request-Type: GraphQL

query GetUser($id: ID, $email: String){
  user(id:$id, email: $email){
    id
    email
    firstName
    lastName
    isStaff
    isActive
  }
}

{
  "email": "rexthonyy@gmail.com"
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREE1TENKbGJXRnBiQ0k2SW05dmVVQjJMbU52SWl3aWFXRjBJam94TmpVME56ZzVPRE0yZlEuaVZNVkd4WlVZMm40bEdvU3dIUFZpdmxXUTJUbjB1ZlFEbWRPTnBpV1ZnRSIsImlhdCI6MTY1NDc4OTgzNiwiZXhwIjoxNjU0NzkwMTM2LCJzdWIiOiIxMDA5In0.ubiA7Py0od4mYNnR_uw0qVhEJMRoWvpwPB-er-PK8Cs
X-Request-Type: GraphQL

mutation{
  passwordChange(newPassword: "secret", oldPassword: "password"){
    user{
      id
      email
      firstName
      lastName
    }
    errors{
      field
      message
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREE1TENKbGJXRnBiQ0k2SW05dmVVQjJMbU52SWl3aWFXRjBJam94TmpVME56a3pNVGs1ZlEuXzN6Wk1mT1pLRnh5ajZuUk9zQ2Nva3EycU82R2Nick9yUm5yT0xjQXNfcyIsImlhdCI6MTY1NDc5MzE5OSwiZXhwIjoxNjU0NzkzNDk5LCJzdWIiOiIxMDA5In0.3ghznrLFfhJQ0mn2W2Dsdkx3q2bagfA20XhUJbRAgS8
X-Request-Type: GraphQL

mutation ChangeEmail($newEmail: String!, $password: String!, $redirectUrl: String!){
  requestEmailChange(
    newEmail: $newEmail
    password: $password
    redirectUrl: $redirectUrl
  ) {
    accountErrors {
      field
      message
    }
    user {
      email
    }
  }
}

{
  "newEmail": "rexthonyy@gmail.com",
  "password": "secret",
  "redirectUrl": "https://google.com"
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazFNVFF4T0gwLm9YbnEteExOeE9hbTR6V1hYcHpKQ2dXdFA5WXVYMFZMNjFmTGQ0ZjNadGciLCJpYXQiOjE2NTQ5NTE0MTgsImV4cCI6MTY1NDk1MTcxOCwic3ViIjoiMTAxMSJ9.L_v2RzLBjpKqs93LC2Fjy3ErMw_VySA_vWnNzZLrsKI
X-Request-Type: GraphQL

mutation AccountUpdate{
  accountUpdate(
    input: {
      firstName: "Leo",
      lastName: "Szillard",
      languageCode: EN,
      defaultBillingAddress: {
        firstName: "new",
        lastName: "york"
      }
    }
  ) {
    accountErrors {
      message
    }
    user {
      email
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazJNVGd3TVgwLkprUF9SZ0dUaXlLVXQwTC1ZR256U0hZZFh6WVl1SjlRbEpMLTdoZXluQnciLCJpYXQiOjE2NTQ5NjE4MDEsImV4cCI6MTY1NDk2MzYwMSwic3ViIjoiMTAxMSJ9.5H5wAligtuiLYSjIXNjP98ji9oRH0ccsSJPTNfR5n-8
X-Request-Type: GraphQL

mutation CustomerUpdate{
  customerUpdate(
    id: 1018,
    input: {
      firstName: "Leo",
      lastName: "Szillard",
      languageCode: EN,
      note: "new customer",
      defaultBillingAddress: {
        firstName: "new",
        lastName: "figi",
        country: NG
      }
    }
  ) {
    accountErrors {
      message
    }
    user {
      email
      defaultBillingAddress{
        firstName
        lastName
      }
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREE1TENKbGJXRnBiQ0k2SW05dmVVQjJMbU52SWl3aWFXRjBJam94TmpVME56a3lNekF4ZlEuQWNSZUJmQ2htU2pUeUcxZGtnei1BYlJsd2N4SUY5eG5RZzU0X0dhcTROayIsImlhdCI6MTY1NDc5MjMwMSwiZXhwIjoxNjU0NzkyNjAxLCJzdWIiOiIxMDA5In0.H4mRCm5ATnfbKGAS7oUky-zt0tcM1G8mNinI4IjyV80
X-Request-Type: GraphQL

mutation ConfirmEmail($token: String!){
  confirmEmailChange(
    token: $token
  ) {
    accountErrors {
      field
      code
    }
    user {
      email
    }
  }
}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXF1ZXN0VHlwZSI6InJlcXVlc3QtZW1haWwtY2hhbmdlIiwiZGF0YSI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeVgybGtJam94TURBNUxDSmxiV0ZwYkNJNkltOXZlVUIyTG1Odklpd2libVYzUlcxaGFXd2lPaUp5WlhoMGFHOXVlWGxBWjIxaGFXd3VZMjl0SWl3aWFXRjBJam94TmpVME56a3pNakV6ZlEuVENYNmNDb0tSQ3JFLUs5VXRwZmJZZGxXaFBlUkxoSUstLTJXNmpDZG9ENCIsImlhdCI6MTY1NDc5MzIxMywiZXhwIjoxNjU0Nzk2ODEzLCJzdWIiOiIxMDA5In0._TQP0rc-XEeZZ29W8xyz-qJYkzEK6s-h_skCcbV-mmA"
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazFPVEl4TVgwLnpZWU50c295WjU2OVpwVFUtMHhQSzNKMExwNDVWQmpPc2paT1FYRmFSWWMiLCJpYXQiOjE2NTQ5NTkyMTEsImV4cCI6MTY1NDk1OTUxMSwic3ViIjoiMTAxMSJ9.WIvtHxDhd4KYlGe-ae-e8zuq0PAyrg-zhLyMgMgzbJA
X-Request-Type: GraphQL

mutation {
  customerCreate(
    input: { 
      firstName: "Kevin",
      lastName: "West",
      languageCode: EN,
      email: "ke@wee.co",
      redirectUrl: "http://google.com",
      isActive: true,
      note: "default-channel",
      defaultShippingAddress: {
        firstName: "sam",
        lastName: "withw",
        companyName: "facebook",
        streetAddress1: "1 street abc",
        streetAddress2: "2 street abc",
        city: "cali",
        cityArea: "cali",
        postalCode: "90023",
        country: BN,
        countryArea: "",
        phone: ""
      },
      defaultBillingAddress: {
        firstName: "sam",
        lastName: "withw",
        companyName: "facebook",
        streetAddress1: "1 street abc",
        streetAddress2: "2 street abc",
        city: "cali",
        cityArea: "cali",
        postalCode: "90023",
        country: BN,
        countryArea: "",
        phone: ""
      }
    }
  ) {
    accountErrors {
      field
      message
    }
    user {
      id
      metadata{
        key
        value
      }
      email
      firstName
      lastName
      isStaff
      isActive
      addresses{
        firstName
        lastName
        companyName
        streetAddress1
        city
      }
    }
  }
}


###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazJOREkyTlgwLkVYTnFyaklPTDZjWXRiOWFrNThnVkoxZXZTUzByMWtGZnpSMEpSNlA5STAiLCJpYXQiOjE2NTQ5NjQyNjUsImV4cCI6MTY1NDk2NjA2NSwic3ViIjoiMTAxMSJ9.igd5kMwfiUcGtZ9q4ip9ZowD_ot_26UPNnLu-bdZjuk
X-Request-Type: GraphQL

mutation {
  staffCreate(
    input: { 
      firstName: "Kevin",
      lastName: "West",
      email: "john@aa.yo",
      redirectUrl: "http://google.com",
      isActive: true,
      note: "default-channel",
      addGroups: [1, 2, 3]
    }
  ) {
    errors {
      field
      message
    }
    user {
      id
      metadata{
        key
        value
      }
      email
      firstName
      lastName
      isStaff
      isActive
      addresses{
        firstName
        lastName
        companyName
        streetAddress1
        city
      }
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazJOREkyTlgwLkVYTnFyaklPTDZjWXRiOWFrNThnVkoxZXZTUzByMWtGZnpSMEpSNlA5STAiLCJpYXQiOjE2NTQ5NjQyNjUsImV4cCI6MTY1NDk2NjA2NSwic3ViIjoiMTAxMSJ9.igd5kMwfiUcGtZ9q4ip9ZowD_ot_26UPNnLu-bdZjuk
X-Request-Type: GraphQL

mutation {
  staffUpdate(
    id: 1011,
    input: { 
      firstName: "Kevin",
      lastName: "West",
      email: "rex@me.co",
      isActive: true,
      note: "default-channel",
      addGroups: [1, 2, 3],
      removeGroups: [1, 2, 3]
    }
  ) {
    errors {
      field
      message
    }
    user {
      id
      email
      firstName
      lastName
      isStaff
      isActive
      addresses{
        firstName
        lastName
        companyName
        streetAddress1
        city
      }
    }
  }
}


###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV3TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1ZVVCbmJXRnBiQzVqYjIwaUxDSnBZWFFpT2pFMk5UUTROakUyTWpWOS43WHBVWGJ1VHh6Y0h5bWxJWXlzS1BpMEFrVkh0b1JmN0pQZVRCSm00R1NVIiwiaWF0IjoxNjU0ODYxNjI1LCJleHAiOjE2NTQ4NjE5MjUsInN1YiI6IjEwMTAifQ.dRb8i91JiGrHG9vN7osiQ8QqfqFCn7Hxi27UpnHo81M
X-Request-Type: GraphQL

mutation RequestAccountDelete($redirectUrl: String!){
  accountRequestDeletion(redirectUrl: $redirectUrl) {
    accountErrors {
      field
      message
      code
    }
  }
}

{
  "redirectUrl": "https://google.com"
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV3TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1ZVVCbmJXRnBiQzVqYjIwaUxDSnBZWFFpT2pFMk5UUTROakkyTURsOS5xS3M3b1V3YWF6UTlra1BLclE0RmVsWk4zcFkxZ2pBd3M4bHFuTXd0NTBNIiwiaWF0IjoxNjU0ODYyNjA5LCJleHAiOjE2NTQ4NjI5MDksInN1YiI6IjEwMTAifQ.8s1iaFQIOrJFJBbX_4nbwOUkJ3pDlX_uViSwJGMQNNg
X-Request-Type: GraphQL

mutation AccountDelete($token: String!){
  accountDelete(token: $token) {
    accountErrors {
      field
      message
    }
    user{
      id
      email
      firstName
      lastName
    }
  }
}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXF1ZXN0VHlwZSI6InJlcXVlc3QtYWNjb3VudC1kZWxldGUiLCJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV3TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1ZVVCbmJXRnBiQzVqYjIwaUxDSnBZWFFpT2pFMk5UUTROakUyTlRkOS40RzQ1a2V6QmdUREdVMEc2SUpoUDRtendpOW1uekQ3dE13eXY1c0RwRmpvIiwiaWF0IjoxNjU0ODYxNjU3LCJleHAiOjE2NTQ4NjUyNTcsInN1YiI6IjEwMTAifQ.tNDMmNmiDKPL77-MKYSAgRqYN8ieTUOi1DFPCq7M4cM"
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazJNak0zTm4wLkpIbE5TcktxNEMxNXJuU1pFRW44LTVnT0taaG8zYktvMkhtTzRZWUx3SGMiLCJpYXQiOjE2NTQ5NjIzNzYsImV4cCI6MTY1NDk2NDE3Niwic3ViIjoiMTAxMSJ9.7ifY0JREfNnCC8xj1ePoRMx70aASNRL7N4Sq9hRjptM
X-Request-Type: GraphQL

mutation CustomerDelete($id: ID!){
  customerDelete(id: $id) {
    accountErrors {
      field
      message
    }
    user{
      id
      email
      firstName
      lastName
    }
  }
}

{
  "id": 1014
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVFQnRaUzVqYnlJc0ltbGhkQ0k2TVRZMU5EazJOVGsyT0gwLlFDc29SYmFzNW5iOUpGbV9jdmw1NkRVaGhmTnp6YnA5UlFuaGxxRnJPNEkiLCJpYXQiOjE2NTQ5NjU5NjgsImV4cCI6MTY1NDk2Nzc2OCwic3ViIjoiMTAxMSJ9.m0fAnCkiUcRZUw36d_mzeXjbD_IxhpJ8oc4yK7LIlak
X-Request-Type: GraphQL

mutation StaffDelete($id: ID!){
  staffDelete(id: $id) {
    errors {
      field
      message
    }
    user{
      id
      email
      firstName
      lastName
    }
  }
}

{
  "id": 1020
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVIUm9iMjU1UUdkdFlXbHNMbU52YlNJc0ltbGhkQ0k2TVRZMU5EazJNak0zTm4wLkpIbE5TcktxNEMxNXJuU1pFRW44LTVnT0taaG8zYktvMkhtTzRZWUx3SGMiLCJpYXQiOjE2NTQ5NjIzNzYsImV4cCI6MTY1NDk2NDE3Niwic3ViIjoiMTAxMSJ9.7ifY0JREfNnCC8xj1ePoRMx70aASNRL7N4Sq9hRjptM
X-Request-Type: GraphQL

mutation CustomerBulkDelete($ids: [ID!]!){
  customerBulkDelete(ids: $ids) {
    count
    accountErrors {
      field
      message
    }
  }
}

{
  "ids": [
    1012,
    1013,
    1018
  ]
}


###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVFQnRaUzVqYnlJc0ltbGhkQ0k2TVRZMU5EazJOakl3TTMwLm9vd2NkamJnaVZlY01oUm44SmpLSjRoTUVhdzZFb254RkdJdklPc3dsREEiLCJpYXQiOjE2NTQ5NjYyMDMsImV4cCI6MTY1NDk2ODAwMywic3ViIjoiMTAxMSJ9.hsewYcKQ6vhNAJukNa76ohKptFF7BCtHAEons_5Wmpw
X-Request-Type: GraphQL

mutation {
  userAvatarDelete {
    user{
      firstName
      email
    }
    errors {
      field
      message
    }
  }
}

###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVFQnRaUzVqYnlJc0ltbGhkQ0k2TVRZMU5EazJOakl3TTMwLm9vd2NkamJnaVZlY01oUm44SmpLSjRoTUVhdzZFb254RkdJdklPc3dsREEiLCJpYXQiOjE2NTQ5NjYyMDMsImV4cCI6MTY1NDk2ODAwMywic3ViIjoiMTAxMSJ9.hsewYcKQ6vhNAJukNa76ohKptFF7BCtHAEons_5Wmpw
X-Request-Type: GraphQL

mutation StaffBulkDelete($ids: [ID!]!){
  staffBulkDelete(ids: $ids) {
    count
    errors {
      field
      message
    }
  }
}

{
  "ids": [
    1021,
    1008
  ]
}



###
POST http://88.208.199.175:1410/graphql
Content-Type: application/json
authorization-bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb3hNREV4TENKbGJXRnBiQ0k2SW5KbGVFQnRaUzVqYnlJc0ltbGhkQ0k2TVRZMU5EazJOakl3TTMwLm9vd2NkamJnaVZlY01oUm44SmpLSjRoTUVhdzZFb254RkdJdklPc3dsREEiLCJpYXQiOjE2NTQ5NjYyMDMsImV4cCI6MTY1NDk2ODAwMywic3ViIjoiMTAxMSJ9.hsewYcKQ6vhNAJukNa76ohKptFF7BCtHAEons_5Wmpw
X-Request-Type: GraphQL

mutation UserBulkSetActive($ids: [ID!]!, $isActive: Boolean!){
  userBulkSetActive(ids: $ids, isActive: $isActive) {
    count
    errors {
      field
      message
    }
  }
}

{
  "ids": [
    1015
  ],
  "isActive": true
}

###
POST http://88.208.199.175:2300/graphql
Content-Type: application/json
Authorization: Bearer 329fcbcd-3cc8-43e1-aad7-b3e604
X-Request-Type: GraphQL

query ($id: ID!){
  permissionGroup(id: $id) {
    id
    name
    users {
      email
      firstName
      lastName
      userPermissions{
        code
      }
    }
    permissions {
      code
      name
    }
    userCanManage
  }
}

{
    "id": 1,
    "PERMISSION_MANAGE_USERS": true,
  "PERMISSION_MANAGE_STAFF": true,
  "PERMISSION_IMPERSONATE_USER": true,
  "PERMISSION_MANAGE_APPS": true,
  "PERMISSION_MANAGE_CHANNELS": true,
  "PERMISSION_MANAGE_DISCOUNTS": true,
  "PERMISSION_MANAGE_PLUGINS": true,
  "PERMISSION_MANAGE_GIFT_CARD": true,
  "PERMISSION_MANAGE_MENUS": true,
  "PERMISSION_MANAGE_ORDERS": true,
  "PERMISSION_MANAGE_PAGES": true,
  "PERMISSION_MANAGE_PAGE_TYPES_AND_ATTRIBUTES": true,
  "PERMISSION_HANDLE_PAYMENTS": true,
  "PERMISSION_MANAGE_PRODUCTS": true,
  "PERMISSION_MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES": true,
  "PERMISSION_MANAGE_SHIPPING": true,
  "PERMISSION_MANAGE_SETTINGS": true,
  "PERMISSION_MANAGE_TRANSLATIONS": true,
  "PERMISSION_MANAGE_CHECKOUTS": true,
  "PERMISSION_HANDLE_CHECKOUTS": true
}